#!/bin/bash

#
# Set Hyprland GTK Theme,Icons , Cursor and Fonts
#
# Author: Iglinsc <igli.linux@gmail.com>
#
# Bash script starts here
#



THEME='Blackarch'
ICONS='Blackarch'
FONT='Terminus 10'
CURSOR='Qogirr-Dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
