#!/usr/bin/env bash

#
# Hyprland Lockscreen Script
#
# Author: Iglinsc <igli.linux@gmail.com>
#
# Bash script starts here
#


# Background Image
IMAGE="$HOME/.config/hypr/wallpapers/lockscreen.png"

# Colors
bg='030303'		bgl='202020'		fg='E5E5E5'
red='CC0000'	green='00CD00'		yellow='CECD00'
blue='0000CC'	magenta='CE00CD'	cyan='00CECE'
alpha='00000000'

# CMD
swaylock -f \
	\
	`# General` \
	--ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	\
	`# Appearance` \
	--color ${bg}E6 \
	--font 'JetBrainsMono Nerd Font' --font-size 18 \
	\
	`# Backspace Key` \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	\
	`# Indicator` \
	--indicator-radius 120 \
	--indicator-thickness 10 \
	\
	`# Inside Circle Colors` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	\
	`# Layout Colors` \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	\
	`# Line Colors` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	\
	`# Ring Colors` \
	--ring-color ${cyan} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	\
	`# Separator Color` \
	--separator-color ${bg} \
	\
	`# Text Colors` \
	--text-color ${fg} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg}
