#!/bin/bash

#
# Launch mako  Notifications Script
#
# Author: Iglinsc <igli.linux@gmail.com>
#
# Bash script starts here
#



CONFIG="$HOME/.config/hypr/mako/config"

if [[ ! `pidof mako` ]]; then
	mako --config ${CONFIG}
fi
