#!/bin/bash

#
# Launch Alacritty with Hypr config
#
# Author: Iglinsc <igli.linux@gmail.com>
#
# Bash script starts here
#



# directory
DIR="$HOME/.config/hypr"
CONFIG="$DIR/alacritty/alacritty.yml"

if [ "$1" == "--float" ]; then
	alacritty --class 'alacritty-float,alacritty-float' --config-file "$CONFIG"
elif [ "$1" == "--full" ]; then
	alacritty --class 'Fullscreen,Fullscreen' --config-file "$CONFIG" \
			  -o window.startup_mode=fullscreen \
			  window.padding.x=30 window.padding.y=30 \
			  window.opacity=0.95 font.size=14
else
	alacritty --config-file "$CONFIG"
fi
